production:
  to:                    "you@gmail.com"
  from:                  "me@gmail.com"
  subject:               "WOOF! watch gou noticed your db is not doing nothing!"
  raise_delivery_errors: false
  delivery_method:       "smtp"
  address:               "smtp.gmail.com"
  port:                  587
  domain:                "gmail.com"
  authentication:        "plain"
  user_name:             "you@gmail.com"
  password:              "changeme"
  enable_starttls_auto:  true

development:
  to:                    "you@gmail.com"
  from:                  "me@gmail.com"
  subject:               "WOOF! watch gou noticed your db is not doing nothing!"
  raise_delivery_errors: false
  delivery_method:       "smtp"
  address:               "smtp.gmail.com"
  port:                  587
  domain:                "gmail.com"
  authentication:        "plain"
  user_name:             "you@gmail.com"
  password:              "changeme"
  enable_starttls_auto:  true

test:
  to:                    "you@gmail.com"
  from:                  "me@gmail.com"
  subject:               "WOOF! watch gou noticed your db is not doing nothing!"
  raise_delivery_errors: false
  delivery_method:       "smtp"
  address:               "smtp.gmail.com"
  port:                  587
  domain:                "gmail.com"
  authentication:        "plain"
  user_name:             "you@gmail.com"
  password:              "changeme"
  enable_starttls_auto:  true
